name: CI/CD for Hugging Face Space

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Hugging Face
        run: |
          pip install huggingface_hub
          huggingface-cli login --token ${{ secrets.HGFACESECRET }}

      - name: Clone Hugging Face Space Repository
        run: |
          git clone https://huggingface.co/spaces/NaeemKhilji/Summarizer
          cp -r . Summarizer/
          cd Summarizer

      - name: Push Changes to Hugging Face Space
        run: |
          cd Summarizer
          git config --global user.email "your-email@example.com"
          git config --global user.name "NaeemKhilji"
          git add .
          git commit -m "CI/CD update"
          git push
